using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Novin.Bpmn.Models;
using Novin.Bpmn.V3.Abstractions;
using Novin.Bpmn.V3.Handlers.Gateways;

namespace Novin.Bpmn.V3
{
    /// <summary>
    /// Routes tokens to the appropriate gateway handler based on gateway type
    /// </summary>
    public class BpmnV3GatewayRouter
    {
        private readonly BpmnV3ExclusiveGatewayHandler _exclusiveGatewayHandler;
        private readonly BpmnV3InclusiveGatewayHandler _inclusiveGatewayHandler;
        private readonly BpmnV3ParallelGatewayHandler _parallelGatewayHandler;

        public BpmnV3GatewayRouter(
            BpmnV3ExclusiveGatewayHandler exclusiveGatewayHandler,
            BpmnV3InclusiveGatewayHandler inclusiveGatewayHandler,
            BpmnV3ParallelGatewayHandler parallelGatewayHandler)
        {
            _exclusiveGatewayHandler = exclusiveGatewayHandler ?? throw new ArgumentNullException(nameof(exclusiveGatewayHandler));
            _inclusiveGatewayHandler = inclusiveGatewayHandler ?? throw new ArgumentNullException(nameof(inclusiveGatewayHandler));
            _parallelGatewayHandler = parallelGatewayHandler ?? throw new ArgumentNullException(nameof(parallelGatewayHandler));
        }

        /// <summary>
        /// Routes a token to the appropriate gateway handler
        /// </summary>
        /// <param name="gateway">The gateway element</param>
        /// <param name="token">The token arriving at the gateway</param>
        /// <param name="processInstance">The process instance</param>
        /// <returns>List of new tokens generated by processing the gateway</returns>
        public async Task<List<BpmnV3Token>> RouteTokenAsync(BpmnGateway gateway, BpmnV3Token token, BpmnV3ProcessInstance processInstance)
        {
            if (gateway == null) throw new ArgumentNullException(nameof(gateway));
            if (token == null) throw new ArgumentNullException(nameof(token));
            if (processInstance == null) throw new ArgumentNullException(nameof(processInstance));

            // Select appropriate handler based on gateway type
            IBpmnV3GatewayHandler handler = gateway switch
            {
                BpmnExclusiveGateway _ => _exclusiveGatewayHandler,
                BpmnInclusiveGateway _ => _inclusiveGatewayHandler,
                BpmnParallelGateway _ => _parallelGatewayHandler,
                // Add other gateway types here as they are implemented
                _ => throw new NotSupportedException($"Gateway type {gateway.GetType().Name} is not supported")
            };

            return await handler.HandleGatewayAsync(gateway, token, processInstance);
        }
        
        /// <summary>
        /// Checks if a gateway can merge based on its type and current tokens
        /// </summary>
        public bool CanMerge(BpmnGateway gateway, BpmnV3ProcessInstance processInstance)
        {
            if (gateway == null) throw new ArgumentNullException(nameof(gateway));
            if (processInstance == null) throw new ArgumentNullException(nameof(processInstance));

            // Select appropriate handler based on gateway type
            IBpmnV3GatewayHandler handler = gateway switch
            {
                BpmnExclusiveGateway _ => _exclusiveGatewayHandler,
                BpmnInclusiveGateway _ => _inclusiveGatewayHandler,
                BpmnParallelGateway _ => _parallelGatewayHandler,
                // Add other gateway types here as they are implemented
                _ => throw new NotSupportedException($"Gateway type {gateway.GetType().Name} is not supported")
            };

            return handler.CanMerge(gateway, processInstance);
        }
    }
} 