<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\Novin.Bpmn\Novin.Bpmn.csproj"/>
    </ItemGroup>


    <ItemGroup>
      <None Update="Bpmn\diagram_2.bpmn">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
