using System.Collections.Generic;
using System.Threading.Tasks;
using Novin.Bpmn.Models;

namespace Novin.Bpmn.V3.Abstractions
{
    /// <summary>
    /// Interface for handling gateways in BPMN V3 with dual token strategy.
    /// </summary>
    public interface IBpmnV3GatewayHandler
    {
        /// <summary>
        /// Processes a gateway using dual token strategy (active and inactive tokens).
        /// </summary>
        /// <param name="gateway">The gateway BPMN element</param>
        /// <param name="token">The token arriving at the gateway</param>
        /// <param name="processInstance">The process instance</param>
        /// <returns>List of tokens generated by processing the gateway</returns>
        Task<List<BpmnV3Token>> HandleGatewayAsync(BpmnGateway gateway, BpmnV3Token token, BpmnV3ProcessInstance processInstance);
        
        /// <summary>
        /// Checks if the gateway can be merged based on incoming tokens
        /// </summary>
        /// <param name="gateway">The gateway BPMN element</param>
        /// <param name="processInstance">The process instance</param>
        /// <returns>True if the gateway can be merged, otherwise false</returns>
        bool CanMerge(BpmnGateway gateway, BpmnV3ProcessInstance processInstance);
    }
} 