<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Novin.Bpmn.Engine.Infrastructure</RootNamespace>
    <AssemblyName>Novin.Bpmn.Engine.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.17.0" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.2.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Novin.Bpmn.Engine.Application\Novin.Bpmn.Engine.Application.csproj" />
    <ProjectReference Include="..\Novin.Bpmn.Engine.Domain\Novin.Bpmn.Engine.Domain.csproj" />
  </ItemGroup>

</Project>

