// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novin.Bpmn.Engine.Infrastructure.Persistence;

#nullable disable

namespace Novin.Bpmn.Engine.Infrastructure.Migrations
{
    [DbContext(typeof(BpmnEngineDbContext))]
    [Migration("20251223112105_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BpmnXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_childNodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_currentTokenIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_parentNodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_tokenIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_nextNodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_parentNodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Node", b =>
                {
                    b.OwnsMany("Novin.Bpmn.Engine.Domain.Entities.NodeTokenHistoryEntry", "TokenHistory", b1 =>
                        {
                            b1.Property<Guid>("NodeId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementId")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OutputVariables")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ReachedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TokenId")
                                .HasColumnType("TEXT");

                            b1.HasKey("NodeId", "Id");

                            b1.ToTable("NodeTokenHistoryEntries");

                            b1.WithOwner()
                                .HasForeignKey("NodeId");
                        });

                    b.Navigation("TokenHistory");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Process", b =>
                {
                    b.OwnsMany("Novin.Bpmn.Engine.Domain.Entities.ProcessHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("ProcessId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementId")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ExecutedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("NodeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("NodeName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("TokenId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProcessId", "Id");

                            b1.ToTable("ProcessHistories");

                            b1.WithOwner()
                                .HasForeignKey("ProcessId");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Token", b =>
                {
                    b.OwnsMany("Novin.Bpmn.Engine.Domain.Entities.TokenHistoryEntry", "TokenHistory", b1 =>
                        {
                            b1.Property<Guid>("TokenId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElementId")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("LeftAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("NodeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("NodeName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ReachedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Variables")
                                .HasColumnType("TEXT");

                            b1.HasKey("TokenId", "Id");

                            b1.ToTable("TokenHistoryEntries");

                            b1.WithOwner()
                                .HasForeignKey("TokenId");
                        });

                    b.Navigation("TokenHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
