// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novin.Bpmn.Engine.Infrastructure.Persistence;

#nullable disable

namespace Novin.Bpmn.Engine.Infrastructure.Migrations
{
    [DbContext(typeof(BpmnEngineDbContext))]
    [Migration("20260101112140_3423423443")]
    partial class _3423423443
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BoundaryEventSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundaryElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalJobKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FireCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("HostElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInterrupting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimerExpression")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimerType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TokenScopeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TriggeredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasFilter("[ActivityInstanceId] IS NOT NULL");

                    b.HasIndex("ProcessId", "BoundaryElementId");

                    b.HasIndex("ProcessId", "HostElementId");

                    b.HasIndex("ProcessId", "TokenScopeId")
                        .HasFilter("[TokenScopeId] IS NOT NULL");

                    b.HasIndex("State", "DueAt")
                        .HasFilter("[DueAt] IS NOT NULL");

                    b.HasIndex("Kind", "State", "DueAt")
                        .HasFilter("[Kind] = 'Timer' AND [State] = 'Active' AND [DueAt] IS NOT NULL");

                    b.HasIndex("Kind", "State", "NextDueAtUtc")
                        .HasFilter("[Kind] = 'Timer' AND [State] = 'Active' AND [NextDueAtUtc] IS NOT NULL");

                    b.HasIndex("ProcessId", "State", "Kind");

                    b.ToTable("BoundaryEventSubscriptions", (string)null);
                });

            modelBuilder.Entity("Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occurrences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeInstanceId")
                        .HasFilter("[NodeInstanceId] IS NOT NULL");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId")
                        .HasFilter("[TokenId] IS NOT NULL");

                    b.HasIndex("WorkerId")
                        .HasFilter("[WorkerId] IS NOT NULL");

                    b.HasIndex("ProcessId", "Status", "LastOccurredAtUtc");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("ProcessId", "Status");

                    b.HasIndex("Status", "LockedUntilUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BpmnHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BpmnXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeployedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.NodeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExecutable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("_arrivedViaFlowIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ArrivedViaFlowIds");

                    b.Property<string>("_variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Variables");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .HasDatabaseName("IX_NodeInstance_TokenId");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasDatabaseName("IX_NodeInstance_Process_ActivityInstance")
                        .HasFilter("[ActivityInstanceId] IS NOT NULL");

                    b.HasIndex("ProcessId", "ElementId")
                        .HasDatabaseName("IX_NodeInstance_Process_Element");

                    b.HasIndex("ProcessId", "ScopeId")
                        .HasDatabaseName("IX_NodeInstance_Process_Scope")
                        .HasFilter("[ScopeId] IS NOT NULL");

                    b.HasIndex("ProcessId", "State")
                        .HasDatabaseName("IX_NodeInstance_Process_State");

                    b.HasIndex("TokenId", "State")
                        .HasDatabaseName("IX_NodeInstance_TokenId_State");

                    b.HasIndex("WorkerId", "State")
                        .HasDatabaseName("IX_NodeInstance_WorkerId_State")
                        .HasFilter("[WorkerId] IS NOT NULL");

                    b.HasIndex("ProcessId", "ElementId", "CreatedAtUtc")
                        .HasDatabaseName("IX_NodeInstance_Process_Element_Created");

                    b.HasIndex("ProcessId", "State", "CreatedAtUtc")
                        .HasDatabaseName("IX_NodeInstance_Process_State_Created");

                    b.ToTable("NodeInstances", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("IX_OutboxMessages_AggregateId")
                        .HasFilter("[AggregateId] IS NOT NULL");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("Status", "LockedUntilUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_LockedUntil")
                        .HasFilter("[Status] = 1 AND [LockedUntilUtc] IS NOT NULL");

                    b.HasIndex("PartitionKey", "Status", "OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_PartitionKey_Status_Occurred")
                        .HasFilter("[PartitionKey] IS NOT NULL");

                    b.HasIndex("Status", "OccurredOnUtc", "NextAttemptOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_Occurred_NextAttempt")
                        .HasFilter("[Status] IN (0, 3)");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessBpmnId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("_nodeInstanceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NodeInstanceIds");

                    b.Property<string>("_tokenIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TokenIds");

                    b.Property<string>("_variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Variables");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("DeploymentId", "ProcessBpmnId");

                    b.HasIndex("ProjectId", "BusinessKey")
                        .HasFilter("[BusinessKey] IS NOT NULL");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.HasIndex("ProjectId", "State");

                    b.ToTable("Processes", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExecutable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("_arrivedViaFlowIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ArrivedViaFlowIds");

                    b.Property<string>("_variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Variables");

                    b.HasKey("Id");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("IX_Token_ParentTokenId")
                        .HasFilter("[ParentTokenId] IS NOT NULL");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasDatabaseName("IX_Token_Process_ActivityInstance")
                        .HasFilter("[ActivityInstanceId] IS NOT NULL");

                    b.HasIndex("ProcessId", "ScopeId")
                        .HasDatabaseName("IX_Token_Process_Scope")
                        .HasFilter("[ScopeId] IS NOT NULL");

                    b.HasIndex("ProcessId", "State")
                        .HasDatabaseName("IX_Token_Process_State");

                    b.HasIndex("ProcessId", "CurrentElementId", "State")
                        .HasDatabaseName("IX_Token_Process_Element_State");

                    b.HasIndex("ScopeId", "CurrentElementId", "State")
                        .HasDatabaseName("IX_Token_Scope_Element_State")
                        .HasFilter("[ScopeId] IS NOT NULL");

                    b.ToTable("Tokens", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.UserTaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("ProcessId", "Status", "CreatedAtUtc");

                    b.ToTable("UserTasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
