// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novin.Bpmn.Engine.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Novin.Bpmn.Engine.Infrastructure.Migrations
{
    [DbContext(typeof(BpmnEngineDbContext))]
    partial class BpmnEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoundaryEventSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("BoundaryElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalJobKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FireCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("HostElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsInterrupting")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastFiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TimerExpression")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TimerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TokenScopeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TriggeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasFilter("\"ActivityInstanceId\" IS NOT NULL");

                    b.HasIndex("ProcessId", "TokenScopeId")
                        .HasFilter("\"TokenScopeId\" IS NOT NULL");

                    b.HasIndex("State", "DueAt")
                        .HasFilter("\"DueAt\" IS NOT NULL");

                    b.HasIndex("Kind", "State", "DueAt")
                        .HasFilter("\"Kind\" = 'Timer' AND \"State\" = 'Active' AND \"DueAt\" IS NOT NULL");

                    b.HasIndex("Kind", "State", "NextDueAtUtc")
                        .HasFilter("\"Kind\" = 'Timer' AND \"State\" = 'Active' AND \"NextDueAtUtc\" IS NOT NULL");

                    b.ToTable("BoundaryEventSubscriptions", (string)null);
                });

            modelBuilder.Entity("Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Occurrences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeInstanceId")
                        .HasFilter("\"NodeInstanceId\" IS NOT NULL");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId")
                        .HasFilter("\"TokenId\" IS NOT NULL");

                    b.HasIndex("WorkerId")
                        .HasFilter("\"WorkerId\" IS NOT NULL");

                    b.HasIndex("ProcessId", "Status", "LastOccurredAtUtc");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LeasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("ProcessId", "Status");

                    b.HasIndex("Status", "LockedUntilUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BpmnHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BpmnXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeployedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.ExecutionFlowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Position"));

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("_viaFlowIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ViaFlowIds");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ExecutionFlow_EventKey");

                    b.HasIndex("ProcessId", "OccurredAtUtc")
                        .HasDatabaseName("IX_ExecutionFlow_Process_OccurredAtUtc");

                    b.HasIndex("ProcessId", "Position")
                        .HasDatabaseName("IX_ExecutionFlow_Process_Position");

                    b.HasIndex("ProcessId", "ToElementId")
                        .HasDatabaseName("IX_ExecutionFlow_Process_ToElement");

                    b.HasIndex("TokenId", "Position")
                        .HasDatabaseName("IX_ExecutionFlow_Token_Position");

                    b.HasIndex("ProcessId", "ScopeId", "Position")
                        .HasDatabaseName("IX_ExecutionFlow_Process_Scope_Position")
                        .HasFilter("\"ScopeId\" IS NOT NULL");

                    b.ToTable("ExecutionFlowRecords", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.NodeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsExecutable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.Property<string>("_arrivedViaFlowIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ArrivedViaFlowIds");

                    b.Property<string>("_variablesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VariablesJson");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .HasDatabaseName("IX_NodeInstance_TokenId");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasDatabaseName("IX_NodeInstance_Process_ActivityInstance");

                    b.HasIndex("ProcessId", "ElementId")
                        .HasDatabaseName("IX_NodeInstance_Process_Element");

                    b.HasIndex("ProcessId", "ScopeId")
                        .HasDatabaseName("IX_NodeInstance_Process_Scope");

                    b.HasIndex("ProcessId", "State")
                        .HasDatabaseName("IX_NodeInstance_Process_State");

                    b.HasIndex("TokenId", "State")
                        .HasDatabaseName("IX_NodeInstance_TokenId_State");

                    b.HasIndex("WorkerId", "State")
                        .HasDatabaseName("IX_NodeInstance_WorkerId_State");

                    b.HasIndex("ProcessId", "ElementId", "CreatedAtUtc")
                        .HasDatabaseName("IX_NodeInstance_Process_Element_Created");

                    b.HasIndex("ProcessId", "State", "CreatedAtUtc")
                        .HasDatabaseName("IX_NodeInstance_Process_State_Created");

                    b.ToTable("NodeInstances", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("IX_OutboxMessages_AggregateId")
                        .HasFilter("\"AggregateId\" IS NOT NULL");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId")
                        .HasFilter("\"CorrelationId\" IS NOT NULL");

                    b.HasIndex("Status", "LockedUntilUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_LockedUntil")
                        .HasFilter("\"Status\" = 1 AND \"LockedUntilUtc\" IS NOT NULL");

                    b.HasIndex("PartitionKey", "Status", "OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_PartitionKey_Status_Occurred")
                        .HasFilter("\"PartitionKey\" IS NOT NULL");

                    b.HasIndex("Status", "OccurredOnUtc", "NextAttemptOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_Occurred_NextAttempt")
                        .HasFilter("\"Status\" IN (0, 3)");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProcessBpmnId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("TerminatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("_metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("_nodeInstanceIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NodeInstanceIds");

                    b.Property<string>("_tokenIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TokenIds");

                    b.Property<string>("_variablesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VariablesJson");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("DeploymentId", "ProcessBpmnId");

                    b.HasIndex("ProjectId", "BusinessKey");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.HasIndex("ProjectId", "State");

                    b.ToTable("Processes", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("_arrivedViaFlowIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ArrivedViaFlowIds");

                    b.Property<string>("_scopeStack")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ScopeStack");

                    b.Property<string>("_variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Variables");

                    b.HasKey("Id");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("IX_Token_ParentTokenId")
                        .HasFilter("\"ParentTokenId\" IS NOT NULL");

                    b.HasIndex("ProcessId", "ActivityInstanceId")
                        .HasDatabaseName("IX_Token_Process_ActivityInstance")
                        .HasFilter("\"ActivityInstanceId\" IS NOT NULL");

                    b.HasIndex("ProcessId", "ScopeId")
                        .HasDatabaseName("IX_Token_Process_Scope")
                        .HasFilter("\"ScopeId\" IS NOT NULL");

                    b.HasIndex("ProcessId", "State")
                        .HasDatabaseName("IX_Token_Process_State");

                    b.HasIndex("ProcessId", "CurrentElementId", "State")
                        .HasDatabaseName("IX_Token_Process_Element_State");

                    b.HasIndex("ScopeId", "CurrentElementId", "State")
                        .HasDatabaseName("IX_Token_Scope_Element_State")
                        .HasFilter("\"ScopeId\" IS NOT NULL");

                    b.ToTable("Tokens", (string)null);
                });

            modelBuilder.Entity("Novin.Bpmn.Engine.Domain.Entities.UserTaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NodeInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("NodeInstanceId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("TokenId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("ProcessId", "Status", "CreatedAtUtc");

                    b.ToTable("UserTasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
