namespace Novin.Bpmn.Test.Models;

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnSignal))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnResource))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnPartnerRole))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnPartnerEntity))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnMessage))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnItemDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnInterface))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnEscalation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnError))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnEndPoint))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnDataStore))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCorrelationProperty))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCollaboration))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalConversation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnChoreography))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalChoreographyTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCategory))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnTimerEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnTerminateEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnSignalEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnMessageEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnLinkEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnEscalationEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnErrorEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnConditionalEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCompensateEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCancelEventDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnCallableElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnProcess))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalUserTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalScriptTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalManualTask))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BpmnGlobalBusinessRuleTask))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL")]
[System.Xml.Serialization.XmlRootAttribute("rootElement", Namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL",
    IsNullable = false)]
public abstract partial class BpmnRootElement : BpmnBaseElement
{
}