//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[GeneratedCode("xsd", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace="http://www.omg.org/spec/BPMN/20100524/MODEL")]
[XmlRoot("documentation", Namespace="http://www.omg.org/spec/BPMN/20100524/MODEL", IsNullable=false)]
public partial class BpmnDocumentation {
    
    private XmlNode[] anyField;
    
    private string idField;
    
    private string textFormatField;
    
    public BpmnDocumentation() {
        this.textFormatField = "text/plain";
    }
    
    /// <remarks/>
    [XmlText()]
    [XmlAnyElement()]
    public XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [DefaultValue("text/plain")]
    public string textFormat {
        get {
            return this.textFormatField;
        }
        set {
            this.textFormatField = value;
        }
    }
}